spring:
  datasource:
    url: jdbc:mysql://124.70.104.246:3306/librarySystem?serverTimezone=UTC
    username: root
    password: XMUwwf@4288
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml # mybatis配置文件所在路径
  type-aliases-package: com.example.library.Bean # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml # mapper映射文件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
